{{- if .Values.ingress.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "ssd-virtual-battery.fullname" . }}
  labels:
    {{- include "ssd-virtual-battery.labels" . | nindent 4 }}
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`{{ .Values.ingress.hostname }}`)
      kind: Rule
      services:
        - name: {{ include "ssd-virtual-battery.fullname" . }}
          port: {{ .Values.service.port }}
      {{- if .Values.ingress.middlewares }}
      middlewares:
        {{- toYaml .Values.ingress.middlewares | nindent 8 }}
      {{- end }}
{{- end }}
