apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ssd-virtual-battery.fullname" . }}
  labels:
    {{- include "ssd-virtual-battery.labels" . | nindent 4 }}
type: Opaque
stringData:
  rails-secret-key-base: {{ .Values.rails.secretKeyBase | quote }}
  ims-ssd-username: {{ .Values.ssdApi.username | quote }}
  ims-ssd-password: {{ .Values.ssdApi.password | quote }}
  ims-ssd-point-of-delivery-id: {{ .Values.ssdApi.pointOfDeliveryId | quote }}
  postgres-password: {{ .Values.postgresql.auth.password | quote }}
  postgres-postgres-password: {{ .Values.postgresql.auth.postgresPassword | quote }}
